sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
- bash install.sh
script:
- source env.sh && npm run test
notifications:
  slack: aitem:nDUQ4XTKW6m9VrTW89ByLxtA
deploy:
  app: protected-beach-29469
  provider: heroku
  api_key:
    secure: Q5s15TqzZlq/BfjjYz76LrSR4aibNNzPH++rzReBGh0QaKMo9ohAfz0f0/xEuZrjlNLl8MPdFPDqZ0N2KH3KTAv2lFoqHRYhwstTmRxdiGolrcHZoSBdmU69xhb7UoUUJ1ypEOr4jp8FwEbU8Z0Ofdzgc0AIRe0pipABHKxvd8qyJLZwtto8fEJqknjB40Fi15wQKVRk5jzxEbYn+2w2R+N4Gu49Opfi3xwavO09AlX/xZ/xWnbYUHXSRdJhcs1Egpvx4jQ6Iffwun2abTC169lGvLPmG/TzEOopM/Mkl6zQIt4syEvBGCuiDGoJjXz9FTSn5LA8albbwiKe1sRbdjRGAgOxX+BwfDYFV6jcSsDJ5kF+59BD2CkROI5/lGl1OnmyMcy8rKIRsosCjItIw5MBnmI4gtcECDKamMApObXF/ReE/6MH0XiJS9ObgBkaAHhrxdWlBVp434l/L8i6p850g9P2TQkbvgYyLZjhVnbwxWklqcaqa3WTI1xmYAQw85UzMtKaRAi1d1urggJZIty8H8DIHwrooBiX49JyZTk2OAhzPmEEhBSraZC5Ek832sSDYx8JpgMjxA/cPN19TKTB7dewk7f2TluYAHMHDKZqdzqyWVBk80rGDUFDZPcSNbBW7u1F2sX1XnhsNCKp+wrKR4o4IhPxxeJDu4U5yjA=
